from django.urls import path
from . import views

urlpatterns = [
    path(r'', views.HomePage.as_view(), name='index'),
    path(r'', views.HomePage.as_view(), name='my_account'),
    path(r'', views.HomePage.as_view(), name='checkout'),
    path(r'', views.HomePage.as_view(), name='index_2'),
    path(r'about', views.AboutPage.as_view(), name='about'),
    path(r'', views.HomePage.as_view(), name='shop_3_column'),
    path(r'', views.HomePage.as_view(), name='shop_4_column'),
    path(r'', views.HomePage.as_view(), name='shop_left_sidebar'),
    path(r'', views.HomePage.as_view(), name='shop_right_sidebar'),
    path(r'', views.HomePage.as_view(), name='single_product'),
    path(r'', views.HomePage.as_view(), name='single_product_variable'),
    path(r'', views.HomePage.as_view(), name='single_product_affiliate'),
    path(r'', views.HomePage.as_view(), name='single_product_group'),
    path(r'', views.HomePage.as_view(), name='single_product_tabstyle_2'),
    path(r'', views.HomePage.as_view(), name='single_product_tabstyle_3'),
    path(r'', views.HomePage.as_view(), name='single_product_slider'),
    path(r'', views.HomePage.as_view(), name='single_product_gallery_left'),
    path(r'', views.HomePage.as_view(), name='single_product_gallery_right'),
    path(r'', views.HomePage.as_view(), name='single_product_sticky_left'),
    path(r'', views.HomePage.as_view(), name='single_product_sticky_right'),
    path(r'', views.HomePage.as_view(), name='cart'),
    path(r'', views.HomePage.as_view(), name='checkout'),
    path(r'', views.HomePage.as_view(), name='compare'),
    path(r'', views.HomePage.as_view(), name='wishlist'),
    path(r'', views.HomePage.as_view(), name='my_account'),
    path(r'', views.HomePage.as_view(), name='login'),
    path(r'', views.HomePage.as_view(), name='empty_cart'),
    path(r'', views.HomePage.as_view(), name='shop_left_sidebar'),
    path(r'', views.HomePage.as_view(), name='404'),
    path(r'', views.HomePage.as_view(), name='privacy_policy'),
    path(r'', views.HomePage.as_view(), name='faq'),
    path(r'', views.HomePage.as_view(), name='comming_soon'),
    path(r'', views.HomePage.as_view(), name='blog_grid_left_sidebar'),
    path(r'', views.HomePage.as_view(), name='blog_grid_right_sidebar'),
    path(r'', views.HomePage.as_view(), name='blog_list_left_sidebar'),
    path(r'', views.HomePage.as_view(), name='blog_list_right_sidebar'),
    path(r'', views.HomePage.as_view(), name='blog_single_left_sidebar'),
    path(r'', views.HomePage.as_view(), name='blog_single_right_sidebar'),
    path(r'contact', views.ContactPage.as_view(), name='contact'),
    
]